<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LayananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $layanans = [
            [
                'nama_layanan' => 'Pemeriksaan Umum (Poli umum)',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 9000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan Umum (Poli paru)',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 9000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan Umum (Poli lansia)',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 9000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan Umum (Poli gizi)',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 9000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan Umum (Poli mtbs)',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 9000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan Umum (Poli gigi)',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 9000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan Umum (Poli KIA)',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 9000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'Pemeiksaan Kesehatan (KIR) pelajar',
                'trf_kunjungan' => 4000,
                'layanan_dokter' => 6000,
                'layanan_tindakan' => 0,
                'total_harga' => 10000,
            ],
            [
                'nama_layanan' => 'Pemeiksaan Kesehatan (KIR) Umum',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 9000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan Calon Pengantin',
                'trf_kunjungan' => 21000,
                'layanan_dokter' => 14000,
                'layanan_tindakan' => 0,
                'total_harga' => 35000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan KIR SIM',
                'trf_kunjungan' => 15000,
                'layanan_dokter' => 10000,
                'layanan_tindakan' => 0,
                'total_harga' => 25000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan Haji Lanjutan',
                'trf_kunjungan' => 40000,
                'layanan_dokter' => 60000,
                'layanan_tindakan' => 0,
                'total_harga' => 100000,
            ],
            [
                'nama_layanan' => 'USG Abdomen Dasar',
                'trf_kunjungan' => 60000,
                'layanan_dokter' => 40000,
                'layanan_tindakan' => 0,
                'total_harga' => 100000,
            ],
            [
                'nama_layanan' => 'USG Kandungan',
                'trf_kunjungan' => 30000,
                'layanan_dokter' => 30000,
                'layanan_tindakan' => 0,
                'total_harga' => 60000,
            ],
            [
                'nama_layanan' => 'Cabut Gigi Susu',
                'trf_kunjungan' => 25000,
                'layanan_dokter' => 15000,
                'layanan_tindakan' => 0,
                'total_harga' => 40000,
            ],
            [
                'nama_layanan' => 'Cabut Gigi Susu dengan Penyulit',
                'trf_kunjungan' => 30000,
                'layanan_dokter' => 20000,
                'layanan_tindakan' => 0,
                'total_harga' => 50000,
            ],
            [
                'nama_layanan' => 'Pencabutan Gigi Tetap seri taring Premolar 1 dan 2',
                'trf_kunjungan' => 30000,
                'layanan_dokter' => 30000,
                'layanan_tindakan' => 0,
                'total_harga' => 60000,
            ],
            [
                'nama_layanan' => 'Pencabutan Gigi Molar',
                'trf_kunjungan' => 25000,
                'layanan_dokter' => 50000,
                'layanan_tindakan' => 0,
                'total_harga' => 75000,
            ],
            [
                'nama_layanan' => 'Pencabutan Gigi tetap dengan penyulit',
                'trf_kunjungan' => 40000,
                'layanan_dokter' => 60000,
                'layanan_tindakan' => 0,
                'total_harga' => 100000,
            ],
            [
                'nama_layanan' => 'Scaling Ringan',
                'trf_kunjungan' => 15000,
                'layanan_dokter' => 20000,
                'layanan_tindakan' => 0,
                'total_harga' => 35000,
            ],
            [
                'nama_layanan' => 'kosasi',
                'trf_kunjungan' => 12000,
                'layanan_dokter' => 18000,
                'layanan_tindakan' => 0,
                'total_harga' => 30000,
            ],
            [
                'nama_layanan' => 'Perawatan Pulp Capping',
                'trf_kunjungan' => 14000,
                'layanan_dokter' => 21000,
                'layanan_tindakan' => 0,
                'total_harga' => 35000,
            ],
            [
                'nama_layanan' => 'Tumpatan Glassiomer Kecil',
                'trf_kunjungan' => 20000,
                'layanan_dokter' => 30000,
                'layanan_tindakan' => 0,
                'total_harga' => 50000,
            ],
            [
                'nama_layanan' => 'Tumpatan Glassiomer Sedang',
                'trf_kunjungan' => 25000,
                'layanan_dokter' => 35000,
                'layanan_tindakan' => 0,
                'total_harga' => 60000,
            ],
            [
                'nama_layanan' => 'Tumpatan Glassiomer Besar',
                'trf_kunjungan' => 35000,
                'layanan_dokter' => 35000,
                'layanan_tindakan' => 0,
                'total_harga' => 70000,
            ],
            [
                'nama_layanan' => 'Tumpatan Sementara',
                'trf_kunjungan' => 10000,
                'layanan_dokter' => 5000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'Tumpatan Composit Kecil',
                'trf_kunjungan' => 60000,
                'layanan_dokter' => 40000,
                'layanan_tindakan' => 0,
                'total_harga' => 100000,
            ],
            [
                'nama_layanan' => 'Tumpatan Composit Sedang',
                'trf_kunjungan' => 75000,
                'layanan_dokter' => 50000,
                'layanan_tindakan' => 0,
                'total_harga' => 125000,
            ],
            [
                'nama_layanan' => 'Tumpatan Composit Besar',
                'trf_kunjungan' => 90000,
                'layanan_dokter' => 60000,
                'layanan_tindakan' => 0,
                'total_harga' => 150000,
            ],
            [
                'nama_layanan' => 'Incisi Abses Intra oral',
                'trf_kunjungan' => 20000,
                'layanan_dokter' => 30000,
                'layanan_tindakan' => 0,
                'total_harga' => 50000,
            ],
            [
                'nama_layanan' => 'Operculectomy',
                'trf_kunjungan' => 60000,
                'layanan_dokter' => 90000,
                'layanan_tindakan' => 0,
                'total_harga' => 150000,
            ],
            [
                'nama_layanan' => 'Koreksi Okluksi',
                'trf_kunjungan' => 16000,
                'layanan_dokter' => 24000,
                'layanan_tindakan' => 0,
                'total_harga' => 40000,
            ],
            [
                'nama_layanan' => 'Penatalaksanaan Perdarahan',
                'trf_kunjungan' => 10000,
                'layanan_dokter' => 15000,
                'layanan_tindakan' => 0,
                'total_harga' => 25000,
            ],
            [
                'nama_layanan' => 'Ginggitectomy',
                'trf_kunjungan' => 40000,
                'layanan_dokter' => 60000,
                'layanan_tindakan' => 0,
                'total_harga' => 100000,
            ],
            [
                'nama_layanan' => 'Scaling Sedang',
                'trf_kunjungan' => 20000,
                'layanan_dokter' => 25000,
                'layanan_tindakan' => 0,
                'total_harga' => 45000,
            ],
            [
                'nama_layanan' => 'DR analyzer (ABACUS)',
                'trf_kunjungan' => 24000,
                'layanan_dokter' => 16000,
                'layanan_tindakan' => 0,
                'total_harga' => 40000,
            ],
            [
                'nama_layanan' => 'hemoglobin',
                'trf_kunjungan' => 9000,
                'layanan_dokter' => 6000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'hitung lekosit',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 4000,
                'layanan_tindakan' => 0,
                'total_harga' => 10000,
            ],
            [
                'nama_layanan' => 'hitung eritrisi',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 4000,
                'layanan_tindakan' => 0,
                'total_harga' => 10000,
            ],
            [
                'nama_layanan' => 'hitung trombosit',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 4000,
                'layanan_tindakan' => 0,
                'total_harga' => 10000,
            ],
            [
                'nama_layanan' => 'hematokrit',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 4000,
                'layanan_tindakan' => 0,
                'total_harga' => 10000,
            ],
            [
                'nama_layanan' => 'golongan darah',
                'trf_kunjungan' => 9000,
                'layanan_dokter' => 6000,
                'layanan_tindakan' => 0,
                'total_harga' => 15000,
            ],
            [
                'nama_layanan' => 'HBSAG rapid tes',
                'trf_kunjungan' => 18000,
                'layanan_dokter' => 12000,
                'layanan_tindakan' => 0,
                'total_harga' => 30000,
            ],
            [
                'nama_layanan' => 'Asam Urat',
                'trf_kunjungan' => 15000,
                'layanan_dokter' => 10000,
                'layanan_tindakan' => 0,
                'total_harga' => 25000,
            ],
            [
                'nama_layanan' => 'Cholestrol',
                'trf_kunjungan' => 21000,
                'layanan_dokter' => 14000,
                'layanan_tindakan' => 0,
                'total_harga' => 35000,
            ],
            [
                'nama_layanan' => 'Gula darah',
                'trf_kunjungan' => 12000,
                'layanan_dokter' => 8000,
                'layanan_tindakan' => 0,
                'total_harga' => 20000,
            ],
            [
                'nama_layanan' => 'Urune Rutin',
                'trf_kunjungan' => 12000,
                'layanan_dokter' => 18000,
                'layanan_tindakan' => 0,
                'total_harga' => 30000,
            ],
            [
                'nama_layanan' => 'Protein urin',
                'trf_kunjungan' => 7200,
                'layanan_dokter' => 4800,
                'layanan_tindakan' => 0,
                'total_harga' => 12000,
            ],
            [
                'nama_layanan' => 'Tes kehamilan',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 15000,
                'layanan_tindakan' => 0,
                'total_harga' => 21000,
            ],
            [
                'nama_layanan' => 'Reduksi',
                'trf_kunjungan' => 2000,
                'layanan_dokter' => 5000,
                'layanan_tindakan' => 0,
                'total_harga' => 7000,
            ],
            [
                'nama_layanan' => 'NS1',
                'trf_kunjungan' => 66000,
                'layanan_dokter' => 44000,
                'layanan_tindakan' => 0,
                'total_harga' => 110000,
            ],
            [
                'nama_layanan' => 'Igd/igd dengue',
                'trf_kunjungan' => 66000,
                'layanan_dokter' => 44000,
                'layanan_tindakan' => 0,
                'total_harga' => 110000,
            ],
            [
                'nama_layanan' => 'HIV',
                'trf_kunjungan' => 42000,
                'layanan_dokter' => 28000,
                'layanan_tindakan' => 0,
                'total_harga' => 70000,
            ],
            [
                'nama_layanan' => 'Syphilis rapid tes',
                'trf_kunjungan' => 15000,
                'layanan_dokter' => 10000,
                'layanan_tindakan' => 0,
                'total_harga' => 25000,
            ],
            [
                'nama_layanan' => 'Coronavirus rapid test',
                'trf_kunjungan' => 69000,
                'layanan_dokter' => 30000,
                'layanan_tindakan' => 0,
                'total_harga' => 99000,
            ],
            [
                'nama_layanan' => 'Sputum BTA',
                'trf_kunjungan' => 12000,
                'layanan_dokter' => 8000,
                'layanan_tindakan' => 0,
                'total_harga' => 20000,
            ],
            [
                'nama_layanan' => 'Sampling darah vena',
                'trf_kunjungan' => 3000,
                'layanan_dokter' => 5000,
                'layanan_tindakan' => 0,
                'total_harga' => 8000,
            ],
            [
                'nama_layanan' => 'Sampling darah kapiler',
                'trf_kunjungan' => 2000,
                'layanan_dokter' => 3000,
                'layanan_tindakan' => 0,
                'total_harga' => 5000,
            ],
            [
                'nama_layanan' => 'Pengambilan Swab Tenggorok',
                'trf_kunjungan' => 10000,
                'layanan_dokter' => 15000,
                'layanan_tindakan' => 0,
                'total_harga' => 25000,
            ],
            [
                'nama_layanan' => 'Pemasangan Implan (oleh Bidan)',
                'trf_kunjungan' => 40000,
                'layanan_dokter' => 60000,
                'layanan_tindakan' => 0,
                'total_harga' => 100000,
            ],
            [
                'nama_layanan' => 'Pelepasan Implan (oleh bidan)',
                'trf_kunjungan' => 40000,
                'layanan_dokter' => 60000,
                'layanan_tindakan' => 0,
                'total_harga' => 100000,
            ],
            [
                'nama_layanan' => 'Pelepasan dan Pemasangan Implan (oleh bidan)',
                'trf_kunjungan' => 60000,
                'layanan_dokter' => 90000,
                'layanan_tindakan' => 0,
                'total_harga' => 150000,
            ],
            [
                'nama_layanan' => 'Pemasangan IUD (oleh Bidan)',
                'trf_kunjungan' => 60000,
                'layanan_dokter' => 90000,
                'layanan_tindakan' => 0,
                'total_harga' => 150000,
            ],
            [
                'nama_layanan' => 'Pelepasan IUD (oleh Bidan)',
                'trf_kunjungan' => 60000,
                'layanan_dokter' => 90000,
                'layanan_tindakan' => 0,
                'total_harga' => 150000,
            ],
            [
                'nama_layanan' => 'Pelepasan Dan Pemasangan IUD (oleh bidan)',
                'trf_kunjungan' => 80000,
                'layanan_dokter' => 120000,
                'layanan_tindakan' => 0,
                'total_harga' => 200000,
            ],
            [
                'nama_layanan' => 'kontrol IUD',
                'trf_kunjungan' => 8000,
                'layanan_dokter' => 18000,
                'layanan_tindakan' => 0,
                'total_harga' => 26000,
            ],
            [
                'nama_layanan' => 'Suntik KB',
                'trf_kunjungan' => 8000,
                'layanan_dokter' => 12000,
                'layanan_tindakan' => 0,
                'total_harga' => 20000,
            ],
            [
                'nama_layanan' => 'Peket Rawat Inap (perhari)',
                'trf_kunjungan' => 80000,
                'layanan_dokter' => 120000,
                'layanan_tindakan' => 0,
                'total_harga' => 200000,
            ],
            [
                'nama_layanan' => 'Paket Rawat ruang Bersalin (perhari)',
                'trf_kunjungan' => 320000,
                'layanan_dokter' => 480000,
                'layanan_tindakan' => 0,
                'total_harga' => 800000,
            ],
            [
                'nama_layanan' => 'Paket Rawat Ruang Isolasi (Perhari)',
                'trf_kunjungan' => 50000,
                'layanan_dokter' => 70000,
                'layanan_tindakan' => 0,
                'total_harga' => 120000,
            ],
            [
                'nama_layanan' => 'Pemakain Inkubator (perhari)',
                'trf_kunjungan' => 30000,
                'layanan_dokter' => 20000,
                'layanan_tindakan' => 0,
                'total_harga' => 50000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan rawat darurat (2jam pertama)',
                'trf_kunjungan' => 20000,
                'layanan_dokter' => 30000,
                'layanan_tindakan' => 0,
                'total_harga' => 50000,
            ],
            [
                'nama_layanan' => 'observasi/Stabilisasi (Per jam)',
                'trf_kunjungan' => 10000,
                'layanan_dokter' => 15000,
                'layanan_tindakan' => 0,
                'total_harga' => 25000,
            ],
            [
                'nama_layanan' => 'Resusitasi RJP/CPR',
                'trf_kunjungan' => 25000,
                'layanan_dokter' => 75000,
                'layanan_tindakan' => 0,
                'total_harga' => 100000,
            ],
            [
                'nama_layanan' => 'Jahit luka persimpul (>10)',
                'trf_kunjungan' => 4000,
                'layanan_dokter' => 6000,
                'layanan_tindakan' => 0,
                'total_harga' => 10000,
            ],
            [
                'nama_layanan' => 'Perawatan Darurat Luka Bakar >10%',
                'trf_kunjungan' => 54000,
                'layanan_dokter' => 84000,
                'layanan_tindakan' => 0,
                'total_harga' => 138000,
            ],
            [
                'nama_layanan' => 'insisi abses',
                'trf_kunjungan' => 12000,
                'layanan_dokter' => 18000,
                'layanan_tindakan' => 0,
                'total_harga' => 30000,
            ],
            [
                'nama_layanan' => 'ekstraksi kuku (perkuku)',
                'trf_kunjungan' => 40000,
                'layanan_dokter' => 60000,
                'layanan_tindakan' => 0,
                'total_harga' => 100000,
            ],
            [
                'nama_layanan' => 'Pemakaian Nebulizer',
                'trf_kunjungan' => 15000,
                'layanan_dokter' => 35000,
                'layanan_tindakan' => 0,
                'total_harga' => 50000,
            ],
            [
                'nama_layanan' => 'Partus Normal (oleh bidan)',
                'trf_kunjungan' => 175000,
                'layanan_dokter' => 525000,
                'layanan_tindakan' => 0,
                'total_harga' => 700000,
            ],
            [
                'nama_layanan' => 'Partus dengan Penyulit (oleh bidan)',
                'trf_kunjungan' => 250000,
                'layanan_dokter' => 750000,
                'layanan_tindakan' => 0,
                'total_harga' => 1000000,
            ],
            [
                'nama_layanan' => 'Resusitasi Bayi Baru Lahir',
                'trf_kunjungan' => 45000,
                'layanan_dokter' => 105000,
                'layanan_tindakan' => 0,
                'total_harga' => 150000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan IVA Test',
                'trf_kunjungan' => 10000,
                'layanan_dokter' => 15000,
                'layanan_tindakan' => 0,
                'total_harga' => 25000,
            ],
            [
                'nama_layanan' => 'Pemeriksaan buta warna',
                'trf_kunjungan' => 6000,
                'layanan_dokter' => 4000,
                'layanan_tindakan' => 0,
                'total_harga' => 10000,
            ],
            [
                'nama_layanan' => 'Scaling Berat',
                'trf_kunjungan' => 23000,
                'layanan_dokter' => 27000,
                'layanan_tindakan' => 0,
                'total_harga' => 50000,
            ],
        ];

        foreach ($layanans as $layanan) {
            DB::table('layanan')->insert([
                'nama_layanan' => $layanan['nama_layanan'],
                'trf_kunjungan' => $layanan['trf_kunjungan'],
                'layanan_dokter' => $layanan['layanan_dokter'],
                'layanan_tindakan' => $layanan['layanan_tindakan'],
                'total_harga' => $layanan['total_harga'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}